### ISSUE TITLE
Criação de ficheiros LI42D-G14

### ISSUE THREAD

**Issue by nrcardeal** [isel-leic-ls/1920-2-common#12]
Boa noite,
Como devemos proceder se o utilizador estiver em modo interativo e escrever dois comandos com o mesmo _filename_? Devemos escrever por cima do ficheiro, não alterar o ficheiro ou juntar de forma coerente o conteúdo antigo do ficheiro com o novo conteúdo?

**Comment by pmhsfelix** [comment]
Escrever "por cima".
