### ISSUE TITLE
Dúvida quanto aos throws na App

### ISSUE THREAD

**Issue by TiagoMMDavid** [isel-leic-ls/1920-2-common#13]
Relativamente à app, caso haja uma exceção (por exemplo um erro a executar um dado comando) é preferível lançar a exceção e consequentemente parar a execução do programa todo ou é melhor apresentar apenas uma mensagem com o respetivo erro continuando a execução de próximos comandos?
Ou seja, quando o guião da demonstração da fase 2 sugere executar comandos que irão dar em erro espera-se qual das opções?

**Comment by pmhsfelix** [comment]
Em modo interactivo, os erros nunca devem terminar a aplicação, excepto se for um erro irrecuperável (e.g. falta de memória). Erros aplicacionais (e.g. parâmetros errados, comando inexistente), nunca devem terminar a aplicação.
