### ISSUE TITLE
Duvida sobre a demonstração

### ISSUE THREAD

**Issue by RainPumpkin** [isel-leic-ls/1920-2-common#14]
Para a demonstração, é obrigatório usar a versão do trabalho do ultimo release da Fase 2 ou pode ser usada uma versão feita após o dia de entrega da Fase 2?

**Comment by fbfreitas** [comment]
Se tiveram de corrigir algum bug, devem fazer uma nova tag (0.2.x) e na demonstração fazem checkout dessa tag.
