### ISSUE TITLE
Review da fluent api implementada pelo grupo 1.

### ISSUE THREAD

**Issue by xploitedd** [isel-leic-ls/1920-2-common#15]
Se fosse possível o grupo 1 gostava de obter _feedback_ sobre a _fluent api_ implementada em `pt.isel.ls.sql.api` e usada em todos os _queries_ à base de dados.

**Comment by pmhsfelix** [comment]
Deixei comentários em [https://github.com/isel-leic-ls/1920-2-LI41D-G01/pull/4#pullrequestreview-408147352]
