### ISSUE TITLE
Different Rooms attributes

### ISSUE THREAD

**Issue by BinaryEnigma01** [isel-leic-ls/1920-2-common#2]
No enunciado da fase 1, há informação diferente sobre os atributos de _Rooms_ :

> A rooms is a physical space that one or more people can use. It is characterized by:
> 
> An unique name.
> A location.
> A person capacity.
> A set of labels, characterizing the room facilities (e.g. video projector availability)

> POST /rooms - creates a new room, given the following parameters
> 
> name - the rooms's name.
> location - the room's location.
> description - the rooms's description.
> label - the set of labels for the room.

A diferença sendo que na primeira informação há um atributo `capacidade`, e na segunda um atributo `descrição`

Devemos implementar ambos ou só um destes atributos?

**Comment by pmhsfelix** [comment]
De preferência ambos. Entretanto, o enunciado já foi alterado para reflectir essa correcção.
Abram este issue se precisarem de mais informação sobre este tema.

**Comment by BinaryEnigma01** [comment]
`description` é um campo opcional?
Faz sentido que seja para que o comando exemplo funcione, mas também poderia ser obrigatorio visto que as alterações ao enunciado podem não ter reflectido isso:
> Example: POST /rooms name=LS3&location=Building F+floor+-1&label=monitors&label=windows

**Comment by pmhsfelix** [comment]
Sim, `description` pode ser considerado um parâmetro opcional.
