### ISSUE TITLE
Can't add GitHub Labels

### ISSUE THREAD

**Issue by BinaryEnigma01** [isel-leic-ls/1920-2-common#3]
O professor mostrou na aula que podiamos adicionar _labels_ aos issues que fizessemos (li41d, por exemplo), mas penso que isto só seja possivel para os gestores do repositorio, como tal, não o posso fazer aqui nem no issue anterior ( #2 )

**Comment by pmhsfelix** [comment]
Não conseguem associar uma label já existente ou não conseguem criar uma nova label?

**Comment by BinaryEnigma01** [comment]
Associar uma label já existente, após pesquisar, isto só é permitido a colaboradores com permissão de escrita:

> Github only allows people with write access to the repository to apply labels (see collaborator access permissions ). I guess it would be too open to abuse otherwise. Unfortunately, the permission is not fine-grained [...].

**Comment by pmhsfelix** [comment]
Obrigado. Não estava a par desse detalhe. Sendo assim, por favor coloquem a turma no descrição do issue. Vou alterar o guia com essa informação. Obrigado.
