### ISSUE TITLE
Informação a apresentar por um comando LI42D-G14

### ISSUE THREAD

**Issue by nrcardeal** [isel-leic-ls/1920-2-common#6]
Boa tarde,

Quando o utilizador utiliza o commando `GET labels/{lid}/rooms` é suposto a informação retornada ser só o _lid_ e o _rid_ ou deveria ser toda a informação de _rooms_, incluíndo as outras _labels_ que ele contem?

**Comment by pmhsfelix** [comment]
Deve ser a lista com todas as salas contendo a _label_ `lid`. Cada entrada dessa lista deve conter: nome, descrição, localização, e capacidade.

Por favor abram o _issue_ de novo se a questão não ficou esclarecida.
