### ISSUE TITLE
Informação a apresentar (GET /rooms | GET /rooms/{rid}) LI42D-G09

### ISSUE THREAD

**Issue by tmrpereira** [isel-leic-ls/1920-2-common#7]
Boa tarde;
Quando são processados os comando `GET /rooms` e `GET /rooms/{rid}` a resposta deverá ser uma lista de salas com as propriedades : Nome, Localização, Capacidade e Descrição? Ou deverá ser também incluido a lista de labels associada a cada sala? 
Obrigado

**Comment by pmhsfelix** [comment]
A lista de labels deve aparecer no detalhe da sala (`GET /rooms/{rid}`), não sendo necessária na listagem de salas.
Por favor re-abra o "issue" caso a dúvida permaneça.
